# Generated by Django 3.2.8 on 2022-02-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0002_auto_20220211_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
