# Generated by Django 3.2.8 on 2022-02-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0005_alter_work_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Work1',
        ),
    ]
