# Generated by Django 3.2.8 on 2022-02-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0010_auto_20220213_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='work1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
    ]
