# Generated by Django 3.2.8 on 2022-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0012_auto_20220215_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work1',
            name='created',
            field=models.DateField(verbose_name='作成日'),
        ),
    ]
