# Generated by Django 3.2.8 on 2022-02-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0013_alter_work1_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='topimage',
        ),
    ]
