# Generated by Django 3.2.8 on 2022-02-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0014_auto_20220215_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work1',
            name='image',
        ),
        migrations.RemoveField(
            model_name='work1',
            name='thumbnail',
        ),
    ]
