# Generated by Django 3.2.8 on 2022-02-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0015_auto_20220215_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サブ画像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='topimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像'),
        ),
        migrations.AddField(
            model_name='work1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
        migrations.AddField(
            model_name='work1',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル'),
        ),
    ]
