# Generated by Django 3.2.8 on 2022-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0018_auto_20220215_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topimage',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='トップ画像'),
        ),
    ]
