# Generated by Django 3.2.8 on 2022-02-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0019_profile_topimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='topimage',
        ),
    ]
