# Generated by Django 3.2.8 on 2022-02-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mino', '0020_remove_profile_topimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subimage',
        ),
    ]
